<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>eb636ca3-9c3e-455b-8532-4993b53fc680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ripple.ripple-surface.ripple-surface-light.btn.btn-primary.btn-lg.w-100.mb-4.btn-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;ĐĂNG NHẬP&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19405bc9-f80e-4ec7-aa97-db03f174fe26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ripple ripple-surface ripple-surface-light btn btn-primary btn-lg w-100 mb-4 btn-register</value>
      <webElementGuid>318bfc31-7c4c-4ba1-a0e3-0c5a8b20f5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86d428e3-b7d8-44c9-b816-59a9bf4a0b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ĐĂNG NHẬP</value>
      <webElementGuid>493a0ce0-6b67-400c-87e0-59467b0884dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[2]/div[@class=&quot;container-fluid  overflow-hidden pb-5 pt-3&quot;]/div[@class=&quot;card mx-5 mb-5 p-5 shadow-5 background-radial-gradient&quot;]/div[@class=&quot;card-body p-5 text-center&quot;]/button[@class=&quot;ripple ripple-surface ripple-surface-light btn btn-primary btn-lg w-100 mb-4 btn-register&quot;]</value>
      <webElementGuid>4297ca08-9c30-4bbc-8b7f-f79aa4063494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/button</value>
      <webElementGuid>1b2630ae-e5b0-4d0a-a2ba-565e865e1c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật khẩu'])[1]/following::button[1]</value>
      <webElementGuid>0e6db6db-a904-470d-b181-9958e15f9525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên tài khoản'])[1]/following::button[1]</value>
      <webElementGuid>00c31fa9-feb0-4c7e-aea2-7f2e3336aa42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[2]/preceding::button[1]</value>
      <webElementGuid>d858188c-73a7-435d-ba78-3807405a8366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023. All rights reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>fe0f042c-6c3d-4ef5-9811-d6c15940acd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d0ceb9c1-a202-40b0-ae68-5994274f382c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'ĐĂNG NHẬP' or . = 'ĐĂNG NHẬP')]</value>
      <webElementGuid>66a06ed2-13f6-4d2c-90db-58da2c602fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
