<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MissingPassword</name>
   <tag></tag>
   <elementGuidId>91cbeaa5-1b69-44e5-a1a5-62e4cd0740b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.alert_message.failed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Vui lòng nhập mật khẩu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>825efe49-1e9d-4ef1-9ee5-6a5639edaa95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert_message failed</value>
      <webElementGuid>4a6546f4-938d-4f92-873f-d93bd86768bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vui lòng nhập mật khẩu</value>
      <webElementGuid>54ed4605-ac6b-45c7-93bb-525d9fb35fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[2]/div[@class=&quot;container-fluid  overflow-hidden pb-5 pt-3&quot;]/div[@class=&quot;card mx-5 mb-5 p-5 shadow-5 background-radial-gradient&quot;]/div[@class=&quot;card-body p-5 text-center&quot;]/div[@class=&quot;alert_message failed&quot;]</value>
      <webElementGuid>1dd74ea2-c12c-4d32-b1cf-3ae6f0fbb282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div</value>
      <webElementGuid>3beac370-3994-436a-b6c1-0899c33ebc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/following::div[5]</value>
      <webElementGuid>e0e7be6e-029b-4b42-915e-2d108804af47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/following::div[5]</value>
      <webElementGuid>61fc21d8-d4aa-4772-93b9-17d6a42d01e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐĂNG NHẬP'])[1]/preceding::div[1]</value>
      <webElementGuid>40cf9891-2207-4235-9813-326a6a3337cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên tài khoản'])[1]/preceding::div[1]</value>
      <webElementGuid>638a5aef-6da2-4f6f-9a5c-e552039143e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vui lòng nhập mật khẩu']/parent::*</value>
      <webElementGuid>0e8fbb19-8e12-420c-a17b-2da5ccd716c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>65b6fb13-9940-43f3-9ba2-76b87a570062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Vui lòng nhập mật khẩu' or . = 'Vui lòng nhập mật khẩu')]</value>
      <webElementGuid>0c61de03-cacb-4852-9f61-c9fd80b4797c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
