<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng k</name>
   <tag></tag>
   <elementGuidId>181731de-9b2e-4e38-85b2-c5fe8e8c6ee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav__items--register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/nav/div[2]/ul/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đăng ký&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4f54195-27f2-40d1-918f-08ed1fd656f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav__items--register</value>
      <webElementGuid>781c4323-2b9f-4353-8007-bb87b035c1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dang-ky</value>
      <webElementGuid>ff7c3605-231e-4adc-9448-13bcd441bc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>be1d1ff8-2274-46e9-ba74-1ceac24aed8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/nav[1]/div[@class=&quot;container-custom nav__container&quot;]/ul[@class=&quot;nav__items&quot;]/ul[1]/li[1]/a[@class=&quot;nav__items--register&quot;]</value>
      <webElementGuid>0406f84a-de4a-4f0e-bfa8-8f1164b8e8ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/nav/div[2]/ul/ul/li/a</value>
      <webElementGuid>7b3ee0f6-e6e3-4b7c-8501-02693d419a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng ký')]</value>
      <webElementGuid>133d0bad-01b6-426c-9cc6-cff33589be6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm baber gần nhất'])[1]/following::a[1]</value>
      <webElementGuid>3c3db633-e862-4048-8deb-0a879a0d8455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hành trình tỏa sáng'])[1]/following::a[2]</value>
      <webElementGuid>05d80216-a9f8-4a14-bf52-a41df5e476e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/preceding::a[1]</value>
      <webElementGuid>13119c27-8062-47ff-875c-232681a39ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng ký']/parent::*</value>
      <webElementGuid>94084cf4-6c1b-4bbc-87b5-2f19fb1e583b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dang-ky')]</value>
      <webElementGuid>4a12bd64-4cf1-4bd8-adb2-022e1e072d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/ul/li/a</value>
      <webElementGuid>6b54715f-71dd-445f-9543-835b500092e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dang-ky' and (text() = 'Đăng ký' or . = 'Đăng ký')]</value>
      <webElementGuid>4639b06c-2357-4d48-bf83-16fc48419cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
