<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng k</name>
   <tag></tag>
   <elementGuidId>d5458b1b-2da8-4cd0-a37e-84373a500a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav__items--register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/nav/div[2]/ul/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đăng ký&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db61c446-3b82-48dc-9ec6-fb713c2474ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav__items--register</value>
      <webElementGuid>96adf80d-693e-4661-939d-67a333915908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dang-ky</value>
      <webElementGuid>13be9943-98d8-4795-84f8-75b98d481256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>c410a25f-6b7e-4a44-9d2c-781bf4d01a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/nav[1]/div[@class=&quot;container-custom nav__container&quot;]/ul[@class=&quot;nav__items&quot;]/ul[1]/li[1]/a[@class=&quot;nav__items--register&quot;]</value>
      <webElementGuid>16dede2c-66ad-4f43-9364-61a6c7b471ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/nav/div[2]/ul/ul/li/a</value>
      <webElementGuid>7672c4c3-28db-471a-8d62-af4484e95540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng ký')]</value>
      <webElementGuid>5c5c22dc-11cb-4475-9ccd-e5aadf39a2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm baber gần nhất'])[1]/following::a[1]</value>
      <webElementGuid>71ebd0d8-da83-44f6-bcb8-0625ac211d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hành trình tỏa sáng'])[1]/following::a[2]</value>
      <webElementGuid>debf0bca-abd5-447e-aed5-da24cef8fed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/preceding::a[1]</value>
      <webElementGuid>edac9266-8c65-4a9e-b79b-3b0b8cb6ce1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng ký']/parent::*</value>
      <webElementGuid>549bf6ab-d78e-4d45-b8ef-a2ada43a34ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dang-ky')]</value>
      <webElementGuid>13516c8d-69db-490c-9a80-45875ad6a5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/ul/li/a</value>
      <webElementGuid>abe949d6-f3f0-427c-94e4-b1f797e2535f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dang-ky' and (text() = 'Đăng ký' or . = 'Đăng ký')]</value>
      <webElementGuid>1164d1f5-5a38-48e1-ba2c-881c277f3888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
