<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , webpack-dev-server-cli_baf6c8</name>
   <tag></tag>
   <elementGuidId>45c7019c-57be-43a3-b1b8-515be64dabb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#webpack-dev-server-client-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='webpack-dev-server-client-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#webpack-dev-server-client-overlay</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>51b3ab29-9f0f-4469-a292-a8ecdd2dda3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>webpack-dev-server-client-overlay</value>
      <webElementGuid>b8cbec90-a9f7-40a2-8c96-6a82a701860d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>d6d22cbe-a6cc-4107-867b-23be7de522c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webpack-dev-server-client-overlay&quot;)</value>
      <webElementGuid>5f2334c6-521b-464a-94f8-0181f8b8fa3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='webpack-dev-server-client-overlay']</value>
      <webElementGuid>fa14db5b-4156-44bf-8cd3-e1f78278df34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e1450420-162d-4766-a9cb-d2be4af682ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'webpack-dev-server-client-overlay' and @src = 'about:blank']</value>
      <webElementGuid>f6e5eb28-07cd-4843-951d-4b130720e13f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
